// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// PostApiContactJSONBody defines parameters for PostApiContact.
type PostApiContactJSONBody string

// PostApiContactRequestBody defines body for PostApiContact for application/json ContentType.
type PostApiContactJSONRequestBody PostApiContactJSONBody
