// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// ClientContact defines model for ClientContact.
type ClientContact struct {

	// email
	Email string `json:"email"`

	// preferred language
	Lang *string `json:"lang,omitempty"`

	// message
	Message string `json:"message"`

	// contact name
	Name string `json:"name"`
}

// PostApiContactJSONBody defines parameters for PostApiContact.
type PostApiContactJSONBody ClientContact

// PostApiContactRequestBody defines body for PostApiContact for application/json ContentType.
type PostApiContactJSONRequestBody PostApiContactJSONBody
