version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
      - .env.local
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    env_file:
      - .env
      - .env.local
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - 8080:8080

volumes:
  db: