openapi: "3.0.0"
info:
  version: 1.0.0
  title: blazhko.tech API
  description: A sample blazhko.tech API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://blazhko.tech/api
paths:
  /api/contact:
    post:
      description: Send data to message handler
      requestBody:
        description: Message to handle
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientContact'
      responses:
        '200':
          description: response from contact form
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    ClientContact:
      title: Client contact request
      type: object
      properties:
        name:
          type: string
          description: contact name
        email:
          type: string
          description: email
        message:
          type: string
          description: message
        lang:
          type: string
          description: preferred language
      required:
        - name
        - email
        - message
